### ISSUE TITLE
Add linting and formatting toolchains

### ISSUE THREAD

**Issue by sudiptog81** [LoginRadius/node-js-sdk#12]
Maintaining a JS code base can get messy as the code base increases in terms of lines of code.

**Comment by indrasen715** [comment]
Hi @sudiptog81 

Thanks for bringing this to our notice and we appreciate your valuable feedback on this.
I will review this feedback with the team, and keep you posted on the progress.

Regards
Indrasen

**Comment by indrasen715** [comment]
HI @sudiptog81 

Thanks for your contribution to this project, this particular request is included in our latest releases version 11.3.0 https://github.com/LoginRadius/node-js-sdk/releases/tag/11.3.0.
Please let me know if you see any other areas of improvement. 

Regards
Indrasen
